import { type SlideData } from './types';

export const AI_TOKEN_ECONOMY_SLIDES_PART1: SlideData[] = [
  {
    id: 'slide-1',
    number: 1,
    sectionNumber: 1,
    beatCode: 'S1.1',
    sectionTitle: { en: 'Intro', de: 'Einleitung' },
    title: { en: 'The Token Economy', de: 'Die Token-Ökonomie' },
    claim: {
      en: 'AI gives teams superpowers, but brings hidden managing responsibilities that previously belonged to staff- or director-level decisions.',
      de: 'KI verleiht Teams Superkräfte, bringt aber Management-Verantwortung mit sich, die bisher auf Director-Ebene lag.',
    },
    notes: {
      en: 'The rush to adopt AI centers almost entirely on engineering velocity, yet every team that embraces it quietly inherits hidden managing responsibilities that previously belonged to staff- or director-level decisions. This operational shift is not confined to software engineers; it directly affects anyone directing an autonomous or semi-autonomous system. When practitioners interact with LLMs, they are no longer just drafting prompts—they are making continuous architectural and budgetary choices regarding compute, attention limits, and model routing. Because these systems bill per token while obscuring the ongoing meter, organizations accumulate silent financial liabilities and degraded outputs without deliberate oversight. The objective is not to memorize per-token pricing tables, but to cultivate an operational fluency that treats compute as a managed resource, balancing raw capability against systemic degradation and cost.',
      de: 'Der Ansturm auf KI fokussiert auf Entwicklungsgeschwindigkeit, doch Teams erben Management-Aufgaben, die früher Director-Ebene betrafen. Praktiker treffen kontinuierlich architektonische und budgetäre Entscheidungen über Compute und Routing.',
    },
    visualType: 'hero',
    highlight: { en: 'Operational Shift', de: 'Operativer Wandel' },
  },
  {
    id: 'slide-2',
    number: 2,
    sectionNumber: 2,
    beatCode: 'S2.1',
    sectionTitle: { en: 'Motivation', de: 'Motivation' },
    title: { en: 'The Freelancer Dilemma', de: 'Das Freelancer-Dilemma' },
    claim: {
      en: 'Imagine a collaborator with encyclopedic knowledge and infinite stamina, who never asks clarifying questions, bills for every word, and remembers nothing.',
      de: 'Stellen Sie sich einen Mitarbeiter vor, der alles weiß und nie müde wird, aber nie Rückfragen stellt, jedes Wort abrechnet und nichts behält.',
    },
    notes: {
      en: 'The freelancer metaphor translates abstract LLM mechanics into intuitive human management terms. On paper, this collaborator arrives with enviable strengths: encyclopedic knowledge, blistering speed, limitless endurance, and an immediate willingness to accept any assignment without hesitation. Crucially, that unquestioning acceptance conceals a major reversal. Taking tasks without asking questions initially looks like frictionless cooperation, but in practice it is a critical flaw. Instead of clarifying ambiguities or flagging missing context, the contractor assumes missing information and rushes ahead. That defect compounds with two others: an extreme eagerness to please that quietly bills the company for every word processed, and complete session amnesia that wipes the slate clean between conversations. Managing an LLM successfully begins with recognizing that beneath the impression of effortless intelligence sits a gifted but amnesic contractor who never clarifies instructions and bills constantly.',
      de: 'Die Freelancer-Metapher übersetzt LLM-Mechanik in Management-Begriffe. Der Mitarbeiter wirkt ideal, aber ungefragtes Annehmen von Aufgaben ist fatal: Statt Unklarheiten zu klären, rät das Modell und rechnet jedes Wort ab, während jede Sitzung bei null beginnt.',
    },
    visualType: 'contrast',
    highlight: { en: 'Strengths vs Flaws', de: 'Stärken vs. Schwächen' },
  },
  {
    id: 'slide-3',
    number: 3,
    sectionNumber: 2,
    beatCode: 'S2.2',
    sectionTitle: { en: 'Motivation', de: 'Motivation' },
    title: { en: 'Lead One, Upskill Many', de: 'Einen führen, viele befähigen' },
    claim: {
      en: 'Practitioners who deliberately manage AI achieve 5–20× throughput; engineering leaders must upskill teams into orchestrators of autonomous workers.',
      de: 'Wer KI aktiv steuert, erzielt 5–20-fachen Durchsatz; Führungskräfte müssen Teams zu Orchestratoren autonomer Agenten weiterbilden.',
    },
    notes: {
      en: 'Adopting the freelancer frame demands a fundamental shift in perspective. Practitioners can choose to opt out of active management and treat AI as a casual novelty, but doing so carries an escalating professional cost. Direct observation across daily engineering practice suggests that individuals who deliberately manage these systems achieve a 5–20× throughput advantage on AI-suited tasks. While that multiplier reflects empirical practice rather than formal research, the market reality is clear: those who ignore it will simply be out-produced. Navigating this divide requires choosing between two doors. Door 1 confronts the individual contributor, who must learn to direct a tireless, amnesic agent without letting token burn or attention drift derail the task. Door 2 addresses the engineering leader, whose mandate is not replacing teams, but upskilling engineers into orchestrators who can responsibly supervise, evaluate, and budget autonomous collaborators at organizational scale.',
      de: 'Praktiker erzielen bei gezielter KI-Führung 5–20× Durchsatz. Für Führungskräfte geht es nicht um den Austausch von Entwicklern, sondern um deren Weiterbildung zu Orchestratoren autonomer Systeme.',
    },
    visualType: 'contrast',
    highlight: { en: '5–20× Throughput', de: '5–20× Durchsatz' },
  },
  {
    id: 'slide-4',
    number: 4,
    sectionNumber: 2,
    beatCode: 'S2.3',
    sectionTitle: { en: 'Motivation', de: 'Motivation' },
    title: { en: 'The Four Eras of AI', de: 'Die vier Epochen der KI' },
    claim: {
      en: 'From Prompt Engineering (Chat) to Context Engineering (Agents), Harness Engineering (Guardrails), and Loop Engineering (Self-improving loops).',
      de: 'Von Prompt Engineering (Chat) über Context Engineering (Agenten) und Harness Engineering (Leitplanken) zu Loop Engineering (Autonome Schleifen).',
    },
    notes: {
      en: 'Whenever technological capabilities outpace human comprehension, new operational disciplines emerge simply to help humans cope. Software itself has always functioned as an abstraction layer between human intent and raw compute; as a former CEO once noted, if users could write raw SQL directly to a database, software applications would not need to exist. In AI, those translation layers are evolving rapidly across four distinct eras. The chat era demanded Prompt Engineering to phrase queries effectively. The agentic era introduced Context Engineering—structuring persistent memory files like AGENTS.md and skills so autonomous systems stay anchored. Today, Harness Engineering surrounds non-deterministic models with deterministic test-and-repair guardrails, paving the way for self-improving Loop Engineering. A frequent mistake today is approaching agentic workflows with an obsolete chat-era mindset. Across every era, however, one foundation persists: the token economy remains the unchanging currency governing compute, attention, and cost.',
      de: 'Vier KI-Epochen: Prompt Engineering im Chat, Context Engineering für Agenten (AGENTS.md, Skills), Harness Engineering mit deterministischen Leitplanken und künftig Loop Engineering. Die Token-Ökonomie bleibt das unveränderliche Fundament.',
    },
    visualType: 'flow',
    highlight: { en: 'Evolutionary Stack', de: 'Entwicklungsstufen' },
  },
  {
    id: 'slide-5',
    number: 5,
    sectionNumber: 2,
    beatCode: 'S2.4',
    sectionTitle: { en: 'Motivation', de: 'Motivation' },
    title: { en: 'The Invisible Invoice', de: 'Die unsichtbare Rechnung' },
    claim: {
      en: 'A €3,200/day external consultant requires multiple signatures and SOW review; agentic workflows burn €120/hr invisibly with zero procurement oversight.',
      de: 'Ein Berater für 3.200 €/Tag erfordert Freigaben und Verträge; Agenten-Workflows verbrennen 120 €/h unbemerkt ohne jede Genehmigung.',
    },
    notes: {
      en: 'In traditional corporate governance, hiring an external contractor requires building an explicit business case, securing budget codes, negotiating statement-of-work documents, and obtaining multiple managerial approvals. In stark contrast, deploying an AI agent involves none of that friction. You don’t negotiate day rates or sign contracts; the tool simply begins processing and billing instantly. When an engineer prompts an agentic framework that makes dozens of iterative tool calls in an hour, that system easily consumes hundreds of thousands of tokens behind the scenes. At peak rates, this silent consumption approaches the equivalent of a €120/hour consultant working completely off the procurement radar. Because the cost accrues continuously in fractions of a cent per request, management often fails to recognize the liability until aggregate cloud invoices arrive at the end of the quarter.',
      de: 'Klassische Berater erfordern Budgetfreigaben und Verträge. Ein KI-Agent dagegen rechnet sofort ab: Dutzende iterative Tool-Aufrufe summieren sich unbemerkt auf ~120 €/h ohne Einkaufsprozess.',
    },
    visualType: 'contrast',
    highlight: { en: 'Unmonitored Burn', de: 'Unkontrollierter Verbrauch' },
  },
  {
    id: 'slide-6',
    number: 6,
    sectionNumber: 2,
    beatCode: 'S2.5',
    sectionTitle: { en: 'Motivation', de: 'Motivation' },
    title: { en: 'Outcome Per Euro', de: 'Ergebnis pro Euro' },
    claim: {
      en: 'Paying 5× more for Opus yields only 4% marginal gain over cheaper models for routine tasks. The competitive advantage belongs to those who optimize outcome per euro.',
      de: '5× höhere Kosten für Opus bringen bei Standardaufgaben oft nur 4% Zuwachs gegenüber günstigen Modellen. Entscheidend ist das Ergebnis pro Euro.',
    },
    notes: {
      en: 'Defaulting to frontier models like Claude Opus for everyday tasks is the engineering equivalent of hiring senior partners to write unit tests. On many routine coding and drafting challenges, spending $100 on an elite model yields a 99% acceptable outcome, whereas allocating $20 to a lighter model like Sonnet or Flash delivers a 95% complete solution. The critical managerial question is whether that final 4% delta justifies an 80% expenditure increase. In most production environments, it does not. The true competitive advantage in the AI era does not belong to the organization that consumes the most compute or buys the most expensive subscriptions; it belongs to teams that ruthlessly optimize outcome per euro, pairing appropriate model tiers to task complexity.',
      de: 'Opus für Routineaufgaben einzusetzen ist wie Senior-Partner für Unit-Tests zu engagieren. 100 $ für 99% Qualität stehen 20 $ für 95% gegenüber. Wettbewerbsvorteile entstehen durch optimierten Ertrag pro Euro.',
    },
    visualType: 'metric',
    highlight: { en: 'Efficiency Metric', de: 'Effizienz-Metrik' },
  },
  {
    id: 'slide-7',
    number: 7,
    sectionNumber: 3,
    beatCode: 'S3.1',
    sectionTitle: { en: 'What Is a Token', de: 'Was ist ein Token' },
    title: { en: 'Billable Tokens & Pricing Spread', de: 'Abrechenbare Tokens & Preisspanne' },
    claim: {
      en: 'A 14× price swing separates frontier reasoning from commodity intelligence ($0.11 DeepSeek vs $0.62 Sonnet vs $1.54 Opus per task).',
      de: 'Eine 14-fache Preisspanne trennt Spitzenmodelle von Basis-KI (0,11 $ DeepSeek vs. 0,62 $ Sonnet vs. 1,54 $ Opus pro Aufgabe).',
    },
    notes: {
      en: 'Large language models do not understand semantics or process dictionary words; they ingest numerical token IDs that average approximately three-quarters of an English word. Every single token passing into or out of an API carries a price tag, and the market pricing spread across contemporary providers is astonishingly wide. For the exact same development task, a baseline execution on DeepSeek V3 costs roughly $0.11, Claude 3.5 Sonnet demands $0.62, and Claude 3.5 Opus surges to $1.54—representing a 14× cost difference. Developing economic intuition for tokens means recognizing that identical prompt sequences produce radically disparate financial footprints depending on model selection.',
      de: 'LLMs verarbeiten keine Wörter, sondern Tokens (~0,75 Wörter). Die Preisspanne für denselben Task reicht von 0,11 $ (DeepSeek) über 0,62 $ (Sonnet) bis zu 1,54 $ (Opus) – eine 14-fache Spreizung.',
    },
    visualType: 'metric',
    highlight: { en: '14× Cost Spread', de: '14× Preisspanne' },
  },
  {
    id: 'slide-8',
    number: 8,
    sectionNumber: 3,
    beatCode: 'S3.2',
    sectionTitle: { en: 'What Is a Token', de: 'Was ist ein Token' },
    title: { en: 'Live Context Breakdown & Boot Tax', de: 'Kontext-Analyse & Boot-Tax' },
    claim: {
      en: 'Before typing a single character, system instructions, MCP tools, and skills consume ~30% of your available context window baseline.',
      de: 'Noch vor dem ersten getippten Buchstaben belegen System-Prompts, Tools und Skills rund 30% des verfügbaren Kontextfensters.',
    },
    notes: {
      en: 'Most commercial interfaces conceal real token expenditure behind synthetic abstractions like message credits or smooth typing animations. Inspecting an agentic environment via tools like /context reveals an immediate reality check: the "context boot tax." In modern development setups equipped with Model Context Protocol (MCP) servers, tool schemas, and local repository skills, the system prompt alone routinely consumes 30% or more of the initial context limit before a user writes a single prompt. Because every subsequent user turn re-transmits that cumulative baseline alongside new inputs, foundational context costs compound relentlessly across prolonged sessions.',
      de: 'In modernen Setups mit MCP-Tools und Skills verbraucht der System-Prompt bereits vor der ersten Benutzereingabe ~30% des Kontextfensters. Diese Boot-Tax wird bei jedem Folgeschritt erneut übertragen.',
    },
    visualType: 'hierarchy',
    highlight: { en: '30% Boot Tax', de: '30% Basiskosten' },
  },
  {
    id: 'slide-9',
    number: 9,
    sectionNumber: 3,
    beatCode: 'S3.3',
    sectionTitle: { en: 'What Is a Token', de: 'Was ist ein Token' },
    title: { en: 'CLI vs Web Tool Obscurity', de: 'CLI vs. Web-Tool-Intransparenz' },
    claim: {
      en: 'Consumer chat tools hide token meters behind fixed $20/month subscriptions; unmonitored consumption creates lock-in and vendor margin.',
      de: 'Web-Chat-Tools verbergen den Zähler hinter 20-$/Monat-Abos; unbemerkter Verbrauch erzeugt Gewöhnung und Anbietermargen.',
    },
    notes: {
      en: 'As an explicit hypothesis rather than an accusation, the obscurity surrounding AI billing in consumer interfaces aligns perfectly with vendor incentives. Flat-rate $20 monthly subscription models deliberately uncouple consumption from cost, encouraging users to adopt token-heavy behavioral habits without friction. Meanwhile, frontier API vendors are engaged in fierce revenue battles, occasionally pricing services below true inference cost simply to capture developer mindshare. By concealing the meter in chat interfaces while exposing raw metrics in developer CLIs, the industry establishes an asymmetry where casual users burn immense compute unconsciously while fluent practitioners leverage direct API access to monitor and optimize every cent.',
      de: 'Pauschale 20-$/Monat-Abos entkoppeln Verbrauch von Kosten und fördern unbedachte Nutzung. Entwickler-Tools (CLI) dagegen machen Token-Kosten transparent und erzwingen wirtschaftliche Disziplin.',
    },
    visualType: 'contrast',
    highlight: { en: 'Hidden Meters', de: 'Versteckte Zähler' },
  },
];
