import { type SlideData } from './types';

export const AI_TOKEN_ECONOMY_SLIDES_PART2: SlideData[] = [
  {
    id: 'slide-10',
    number: 10,
    sectionNumber: 4,
    beatCode: 'S4.1',
    sectionTitle: { en: 'Managing Context', de: 'Kontext steuern' },
    title: { en: 'Attention Span as Context', de: 'Aufmerksamkeitsspanne als Kontext' },
    claim: {
      en: 'The context window functions like human cognitive stamina: fresh in the morning, saturated and prone to reasoning degradation by evening.',
      de: 'Das Kontextfenster gleicht menschlicher Ausdauer: morgens frisch, abends gesättigt und fehleranfällig.',
    },
    notes: {
      en: 'The context window functions like human cognitive stamina across an exhausting workday. A new conversation begins with sharp reasoning and strict rule adherence, comparable to an engineer starting their morning at 9 AM. But as conversation history accumulates, the model’s effective attention span begins to flag. When sessions swell beyond tens of thousands of tokens, models exhibit context rot: instruction drift, missed constraints, and circular reasoning. Recognizing that context limits are an active cognitive boundary rather than an infinite bucket is fundamental to running reliable agentic workflows.',
      de: 'Das Kontextfenster ist eine kognitive Grenze. Mit zunehmender Konversationslänge ermüdet das Modell: Anweisungen verblassen, Richtlinien werden ignoriert und Zirkelschlüsse häufen sich.',
    },
    visualType: 'flow',
    highlight: { en: 'Cognitive Stamina', de: 'Kognitive Ausdauer' },
  },
  {
    id: 'slide-11',
    number: 11,
    sectionNumber: 4,
    beatCode: 'S4.2',
    sectionTitle: { en: 'Managing Context', de: 'Kontext steuern' },
    title: { en: 'The Lost Middle Phenomenon', de: 'Das Phänomen der verlorenen Mitte' },
    claim: {
      en: 'Models attend reliably to the start and end of prompt context, while critical instructions buried in the middle suffer severe recall drop-offs.',
      de: 'Modelle beachten Anfang und Ende des Kontexts zuverlässig, während Anweisungen in der Mitte drastisch übersehen werden.',
    },
    notes: {
      en: 'The degradation of long context windows directly mirrors human memory biases, specifically the serial position effect discovered by psychologist Bennet Murdock in 1962. Extensive empirical research by Liu et al. in "Lost in the Middle" demonstrates that LLMs attend exceptionally well to tokens located at the extreme beginning and end of their input contexts, but experience steep recall drops for information nestled in the center. Placing critical business logic or architectural boundaries into the midsection of a massive prompt almost guarantees that the model will overlook those constraints during reasoning.',
      de: 'Wie das menschliche Gedächtnis unterliegen LLMs dem Serial-Position-Effekt: Anfang und Ende werden beachtet, während die Mitte verwischt. Wichtige Regeln in der Mitte werden oft ignoriert.',
    },
    visualType: 'metric',
    highlight: { en: 'U-Shaped Recall Curve', de: 'U-förmige Aufmerksamkeitskurve' },
  },
  {
    id: 'slide-12',
    number: 12,
    sectionNumber: 4,
    beatCode: 'S4.3',
    sectionTitle: { en: 'Managing Context', de: 'Kontext steuern' },
    title: { en: 'The Fullness Gauge & Smart Zone', de: 'Die Füllstandsanzeige & Smart Zone' },
    claim: {
      en: 'Below 50% capacity is the high-accuracy "Smart Zone". Beyond 50%, proactively compact context, delegate to subagents, or reset sessions.',
      de: 'Unter 50% Füllstand liegt die hochpräzise „Smart Zone“. Ab 50% muss proaktiv kompaktiert, delegiert oder neu gestartet werden.',
    },
    notes: {
      en: 'To prevent reasoning failures, practitioners must operate within the "smart zone"—the lower half of a model’s total context capacity where instruction-following remains pristine. Once usage crosses the 50% threshold, models begin dropping subtle constraints. Maintaining operational reliability requires three proactive levers: constant monitoring via context telemetry, aggressive compaction using automated summarization scripts, and disciplined subagent handoffs that spin off sub-tasks into clean, isolated workspaces before returning synthesized answers.',
      de: 'Für maximale Zuverlässigkeit muss die „Smart Zone“ (&lt;50% Füllstand) gehalten werden. Drei Hebel sichern dies: Kontext-Monitoring, proaktives Kompaktieren und Delegation an Subagenten.',
    },
    visualType: 'metric',
    highlight: { en: 'Smart Zone (<50%)', de: 'Smart Zone (<50%)' },
  },
  {
    id: 'slide-13',
    number: 13,
    sectionNumber: 5,
    beatCode: 'S5.1',
    sectionTitle: { en: 'Cost of Agentic AI', de: 'Kosten agentischer KI' },
    title: { en: 'The 55k Token Bug Fix Walkthrough', de: 'Der 55k-Token-Bugfix-Ablauf' },
    claim: {
      en: 'A seemingly trivial single-line bug fix compounded across multi-turn agent tool executions to accumulate ~73,000 tokens of carried context.',
      de: 'Ein scheinbar simpler Einzeilen-Bugfix summierte sich über mehrstufige Agentenschritte auf ~73.000 Tokens mitgetragenen Kontext.',
    },
    notes: {
      en: 'Agentic workflows do not execute tasks in a single leap; they operate in an iterative loop: read file, interpret error, propose patch, run test suite, and evaluate stdout. Because the complete historical transcript must accompany every subsequent tool invocation, a modest bug fix requiring five interactive cycles can easily accumulate ~73,000 tokens of active context. Over the course of the session, the cumulative input tokens billed across all turns frequently exceeds 226,000 tokens for what appeared on the surface to be a trivial 10-line code modification.',
      de: 'Agenten arbeiten iterativ: Datei lesen, Fehler analysieren, Patch anwenden, Tests ausführen. Da die Historie jedes Mal mitgesendet wird, häuft ein simpler Fix schnell ~73.000 Tokens Kontext an.',
    },
    visualType: 'flow',
    highlight: { en: 'Compounding Loops', de: 'Kaskadierende Schleifen' },
  },
  {
    id: 'slide-14',
    number: 14,
    sectionNumber: 5,
    beatCode: 'S5.2',
    sectionTitle: { en: 'Cost of Agentic AI', de: 'Kosten agentischer KI' },
    title: { en: 'The Compounding Cost Curve', de: 'Die kaskadierende Kostenkurve' },
    claim: {
      en: 'Because history re-sends at every turn, input token billing dominates overall expense; multi-turn agents turn linear tasks into exponential cost curves.',
      de: 'Weil die Historie bei jedem Schritt neu gesendet wird, dominieren Input-Tokens die Kosten; Agenten machen lineare Aufgaben exponentiell teuer.',
    },
    notes: {
      en: 'Here lies the central financial trap of agentic AI: you are billed for tokens processed on input, not just generated on output. In a five-step development sequence, the final step bills you not only for the current 500-word response, but also for reading the 70,000 tokens that came before it. If an engineering organization deploys frontier models blindly across autonomous loops, token spend accelerates exponentially. Unlocking agentic productivity requires building automated gates that prune stale logs and intermediate tool outputs before re-transmission.',
      de: 'Die Kostenfalle agentischer KI: Bei jedem Schritt wird die gesamte Vorgeschichte erneut als Input abgerechnet. Ohne automatisches Beschneiden alter Logs explodieren die Kosten exponentiell.',
    },
    visualType: 'metric',
    highlight: { en: 'Input Re-transmission', de: 'Input-Wiederholung' },
  },
  {
    id: 'slide-15',
    number: 15,
    sectionNumber: 6,
    beatCode: 'S6.1',
    sectionTitle: { en: 'Model Tiers', de: 'Modell-Hierarchien' },
    title: { en: 'Tiered Model Stack Architecture', de: 'Architektur des Modell-Stacks' },
    claim: {
      en: 'Intelligent routing directs high-volume routine execution to cheap/fast models, reserving frontier reasoning tiers for architecture and planning.',
      de: 'Intelligentes Routing leitet Routineaufgaben an günstige Modelle und reserviert Spitzenmodelle für Architektur und Planung.',
    },
    notes: {
      en: 'Achieving economic fluency means designing a tiered model stack that routes every request to the most cost-effective tier qualified to resolve it. Exploration, ideation, and broad repository search belong in Tier 1 with rapid, low-cost models like Flash or Haiku. Specification authoring and task decomposition move to Tier 2 with balanced models like Sonnet. Frontier Tier 3 reasoning (Opus, O1) is reserved strictly for complex architectural design, ambiguous trade-offs, and critical system verification.',
      de: 'Wirtschaftliche KI-Nutzung erfordert ein dreistufiges Modell-Routing: Tier 1 (Haiku/Flash) für Suche & Routine, Tier 2 (Sonnet) für Planung & Code, Tier 3 (Opus/Thinking) nur für komplexe Architektur.',
    },
    visualType: 'hierarchy',
    highlight: { en: '3-Tier Routing', de: '3-Stufen-Routing' },
  },
  {
    id: 'slide-16',
    number: 16,
    sectionNumber: 7,
    beatCode: 'S7.1',
    sectionTitle: { en: 'Tools & Tips', de: 'Werkzeuge & Tipps' },
    title: { en: 'The Operational Playbook', de: 'Das operative Playbook' },
    claim: {
      en: 'Three concrete levers to master token economy: automated context compaction, disciplined agent steering, and institutional team practices.',
      de: 'Drei Hebel zur Beherrschung der Token-Ökonomie: automatisierte Kompaktierung, präzise Agentenführung und Team-Standards.',
    },
    notes: {
      en: 'Improving your token economy involves combining automated tooling with disciplined human habits. Automated levers include pre-commit linting gates, script-based context compaction, and subagent isolation. Agent steering levers demand clear boundaries, concise markdown guidelines, and unambiguous exit criteria. Organizational levers require establishing explicit model tiering policies, sharing high-efficiency prompt patterns, and monitoring team token expenditure dashboards in weekly standups.',
      de: 'Drei Hebel zur Optimierung: Automatisierung (Linting, Kompaktierung, Subagenten), Agentenführung (klare Spezifikationen in Markdown, präzise Limits) und Team-Praxis (Modell-Routing-Vorgaben, Kosten-Reviews).',
    },
    visualType: 'hierarchy',
    highlight: { en: 'Operational Levers', de: 'Operative Hebel' },
  },
  {
    id: 'slide-17',
    number: 17,
    sectionNumber: 8,
    beatCode: 'S8.1',
    sectionTitle: { en: 'Closer', de: 'Abschluss' },
    title: { en: 'Start Building Context', de: 'Beginnen Sie mit dem Kontext' },
    claim: {
      en: 'The token economy rewards structured context above all else: shared rules, clear definitions, and institutional memory scale effortlessly.',
      de: 'Die Token-Ökonomie belohnt strukturierten Kontext: gemeinsame Regeln, klare Definitionen und institutionelles Gedächtnis skalieren mühelos.',
    },
    notes: {
      en: 'The fundamental currency of modern AI systems is not clever prompt phrasing; it is structured, high-signal context. Teams that invest in creating explicit domain definitions, architecture records, and automated verification harnesses enable autonomous agents to execute with clinical precision at minimal token expense. Conversely, teams that neglect context management burn endless compute on ambiguous iterations.',
      de: 'Die wichtigste Währung ist nicht cleveres Prompting, sondern strukturierter, hochpräziser Kontext. Wer Regeln, Architekturen und Prüfmechanismen dokumentiert, lässt Agenten wirtschaftlich arbeiten.',
    },
    visualType: 'metric',
    highlight: { en: 'Structured Context', de: 'Strukturierter Kontext' },
  },
  {
    id: 'slide-18',
    number: 18,
    sectionNumber: 8,
    beatCode: 'S8.2',
    sectionTitle: { en: 'Closer', de: 'Abschluss' },
    title: { en: 'Lead Your People to Lead the AI', de: 'Führen Sie Ihr Team zur KI-Führung' },
    claim: {
      en: 'The competitive divide will not be between organizations that use AI and those that refuse it, but between those who burn tokens blindly and those who manage compute as a disciplined economic resource.',
      de: 'Der Wettbewerbsvorteil entsteht nicht durch den Einsatz von KI allein, sondern durch die Fähigkeit, Rechenleistung wirtschaftlich und diszipliniert zu steuern.',
    },
    notes: {
      en: 'The tireless, amnesic freelancer is now an irreversible reality across the corporate landscape. Those who ignore its management requirements will accumulate uncontrolled token liabilities and degraded technical foundations. The winning organizations will be those that actively train their engineers, product managers, and leaders to treat tokens as a finite economic asset, mastering the discipline of orchestrating autonomous systems to maximize outcome per euro.',
      de: 'Der unermüdliche, aber amnesische Freelancer bleibt. Der Erfolg entscheidet sich daran, ob Teams lernen, KI als wirtschaftliche Ressource zu steuern und das Maximum an Ergebnis pro Euro zu erzielen.',
    },
    visualType: 'contrast',
    highlight: { en: 'Economic Leadership', de: 'Wirtschaftliche Führung' },
  },
];
