import { type SlideData } from './types';

export const MAINTAIN_MARKDOWN_FOR_AI_SLIDES_PART2: SlideData[] = [
  {
    id: 'slide-8',
    number: 8,
    sectionNumber: 5,
    beatCode: 'S5.1',
    sectionTitle: { en: 'Google OKF', de: 'Google OKF' },
    title: { en: 'Google Open Knowledge Format', de: 'Google Open Knowledge Format' },
    claim: {
      en: 'OKF v0.2 standardizes metadata: pairing agent "generated.by" with human "verified.by", defining sources, and establishing "stale_after" dates.',
      de: 'OKF v0.2 standardisiert Metadaten: "generated.by" für Agenten, "verified.by" für Menschen, Quellen und "stale_after"-Ablaufdaten.',
    },
    notes: {
      en: 'Section 04 drew the boundary between machine, AI, and human judgment. This section returns to the machine column and asks how to expand it. A machine operates on structure, and automated verification only functions when teams agree on what metadata fields exist and what they mean. Without shared agreement, no universal checker can be written; every team invents bespoke conventions and nothing composes. Google’s Open Knowledge Format (OKF) is an open standard for markdown frontmatter. Currently in version 0.2 and actively evolving, it standardizes basic metadata ( type , title , description , sources ) alongside critical trust and lifecycle contracts: pairing generated by an agent with verified by a human, and defining stale_after dates. Adopting a shared standard rather than internal convention allows verification tooling to be authored once and executed across any repository—the architectural foundation for section 06.',
      de: "Open Knowledge Format (OKF) von Google: Vereinheitlicht Frontmatter über Repositories hinweg. Trennung von 'generated.by' (Agent) und 'verified.by' (Mensch) sowie 'stale_after' als Verfallsdatum.",
    },
    visualType: 'hierarchy',
    highlight: { en: 'OKF v0.2 Standard', de: 'OKF v0.2 Standard' },
  },
  {
    id: 'slide-9',
    number: 9,
    sectionNumber: 6,
    beatCode: 'S6.1',
    sectionTitle: { en: 'Steering the AI', de: 'Die KI steuern' },
    title: { en: 'markdown-harness', de: 'markdown-harness' },
    claim: {
      en: 'A document should tell you how much of itself to believe: markdown-harness injects deterministic staleness signals directly into the AI runtime.',
      de: 'Ein Dokument muss sagen, wie vertrauenswürdig es ist: markdown-harness speist deterministische Signale direkt in den KI-Agenten ein.',
    },
    notes: {
      en: 'Section 05 closed with the challenge of expanding the machine column beyond simple syntax and date validation. This slide presents markdown-harness as an implementation of that expanded boundary. The core principle of the tool is that a document can tell you how much of itself to believe. Rather than attempting to manufacture semantic trust—a quality no automated system can produce—it establishes an operational floor by emitting reliable, deterministic signals whenever an agent or a human needs to intervene. The visual layout is a deliberate callback to the three-circle model introduced in section 04. While the earlier diagram mapped where verification effort concentrates, this version illustrates how the tooling operates across those same boundaries. The directional steer arrow indicates fast, cheap, deterministic signals injected into the AI runtime to improve contextual judgment—the machine column actively steering the AI column. Crucially, the human circle is greyed out not because human oversight is solved or trivial, but because the tool intentionally stops before it. It treats the section 04 boundary as a permanent design constraint.',
      de: 'markdown-harness als Brücke: Das Tool sorgt dafür, dass Dokumente ihren eigenen Vertrauensstatus deklarieren, und speist Warnungen direkt in den Kontext des KI-Agenten ein, bevor falsche Entscheidungen getroffen werden.',
    },
    visualType: 'flow',
    highlight: { en: 'Runtime Steering', de: 'Laufzeit-Steuerung' },
  },
  {
    id: 'slide-10',
    number: 10,
    sectionNumber: 6,
    beatCode: 'S6.2',
    sectionTitle: { en: 'Steering the AI', de: 'Die KI steuern' },
    title: { en: 'The Deterministic Core', de: 'Der deterministische Kern' },
    claim: {
      en: 'One engine connects 3 triggers (AI runtime, Git pre-commit, Nightly cron) to 3 outcomes (Inject steering, Block commit, Raise ticket).',
      de: 'Eine Engine verbindet 3 Auslöser (KI-Laufzeit, Git-Hook, Cron) mit 3 Ergebnissen (Steuern, Commit blockieren, Ticket erstellen).',
    },
    notes: {
      en: 'The architecture connects three entry points to three corresponding outcomes through a single shared engine. Regardless of how it is invoked, the core executes two discrete steps: retrieving configuration and running deterministic validation logic. Given identical inputs, it produces identical evaluations every time. Three triggers invoke this pipeline. The most critical for this presentation—and the focus of the upcoming live demonstration—is the AI runtime, where an agent attempting to read a file receives immediate notice of staleness before consuming the content. Second is commit time, where a pre-commit check evaluates frontmatter against open standards like OKF to pass or block incoming changes. Third is asynchronous scheduling, executing nightly to regenerate derived indexes or raise tickets for stale content. Determinism here is not a buzzword; invariant behavior in the middle is what makes the resulting signals dependable enough for autonomous agents.',
      de: 'Eine Engine, drei Schnittstellen: Laufzeit-Prüfung im KI-Agenten, Pre-Commit-Hook im Git-Workflow und nächtliche Cron-Jobs zur Generierung von Überprüfungs-Tickets.',
    },
    visualType: 'flow',
    highlight: { en: '3 Triggers → 3 Outcomes', de: '3 Trigger → 3 Outcomes' },
  },
  {
    id: 'slide-11',
    number: 11,
    sectionNumber: 6,
    beatCode: 'S6.3',
    sectionTitle: { en: 'Steering the AI', de: 'Die KI steuern' },
    title: { en: 'Live Enforcement Demo', de: 'Live-Demonstration' },
    claim: {
      en: 'Unhooked models drift or hallucinate stale facts; hooked agents receive deterministic staleness headers that prevent unauthorized execution.',
      de: 'Ungeprüfte Agenten driften ab; mit Harness ausgestattete Agenten erhalten deterministische Warnungen vor veraltetem Kontext.',
    },
    notes: {
      en: 'The demonstration runs three terminal panels side by side against an identical onboarding prompt and document; the only independent variable is what each agent is permitted to know. The un-hooked agent reads raw markdown, while the hooked panels either inject steering instructions or deny access entirely. The central thesis of the demo is determinism versus probability, rather than simple catches versus misses. An un-hooked model might occasionally spot a stale timestamp on its own—especially larger reasoning models—but unassisted detection remains a matter of luck. In contrast, the harness guarantees enforcement on every execution across all models, proving the section 04 machine boundary in practice. For visual clarity in a terminal, the injection tells the agent to respond in pirate—providing unmistakable visual evidence rather than a novelty. Furthermore, runtime logs record staleness deterministically regardless of model output. Crucially, modern models occasionally flag steering prompts as injection attacks and report ignoring them—an acknowledged, open research challenge for runtime document governance.',
      de: 'Live-Vergleich: Ohne Harness überliest das Modell veraltete Zeitstempel. Mit Harness verweigert der Agent die Ausführung veralteter Schritte oder warnt den Anwender explizit vor inhaltlichem Drift.',
    },
    visualType: 'metric',
    highlight: { en: 'Deterministic vs Luck', de: 'Deterministisch' },
  },
  {
    id: 'slide-12',
    number: 12,
    sectionNumber: 6,
    beatCode: 'S6.4',
    sectionTitle: { en: 'Steering the AI', de: 'Die KI steuern' },
    title: { en: 'Feature Roadmap', de: 'Roadmap & Ausblick' },
    claim: {
      en: 'Shipped (v0.0.4): Schema validation, stale date checks, link verification. Planned: Cross-document drift analysis and automated triage.',
      de: 'Bereitgestellt (v0.0.4): Schema-, Datums- und Linkprüfung. Geplant: Analyse von Querverweis-Drift und automatische Triage.',
    },
    notes: {
      en: '[PROVISIONAL] Say the version number out loud. It is v0.0.4 , and the left column is all that exists — three checks. Be explicit that the right column is not built yet. Do not soften this into "and we\'re also working on". If anyone leaves thinking drift detection ships today, the rest of the talk is worth less.',
      de: 'Roadmap: Version 0.0.4 liefert bereits Schema- und Datumsprüfung sowie Link-Validierung. Künftige Versionen adressieren Querverweis-Drift und semantische Abweichungsanalyse.',
    },
    visualType: 'hierarchy',
    highlight: { en: 'v0.0.4 Shipped', de: 'v0.0.4 Veröffentlicht' },
  },
  {
    id: 'slide-13',
    number: 13,
    sectionNumber: 8,
    beatCode: 'S8.1',
    sectionTitle: { en: 'The Verifying Half Is Yours', de: 'Der Verifizierungs-Teil gehört Ihnen' },
    title: { en: 'The Verifying Half Is Yours', de: 'Der prüfende Teil gehört Ihnen' },
    claim: {
      en: 'Machines automate structure, AI accelerates synthesis, but accountability never leaves human hands. Verification is your permanent seat.',
      de: 'Maschinen prüfen Struktur, KI beschleunigt Recherche, aber Verantwortung bleibt beim Menschen. Verifikation ist Ihre Kernaufgabe.',
    },
    notes: {
      en: 'This slide marks the third appearance of the three-circle diagram. Across the talk, the geometry remained constant while emphasis shifted: section 04 mapped verification costs, 06.1 showed markdown-harness steering the AI region while stopping before the human boundary, and here the human circle carries the weight. The talk concludes on one image changing. Machines verify structure, AI accelerates drafting, and the remaining work belongs to human judgment. That is not a failure of tooling; it is where accountability always resided, now visible because generation became cheap. The hypothesis line is highlighted because the AI region remains an unsettled thesis, proven when the demo model detected the steering injection. Finally, the repository link is an invitation rather than a product pitch. The talk succeeds when the maintenance problem is understood, regardless of whether the tool is adopted.',
      de: 'Das Drei-Säulen-Modell zum Abschluss: Maschinen automatisieren Struktur, KI beschleunigt die Vorprüfung, doch Verantwortung und Fachurteil verbleiben dauerhaft beim Menschen.',
    },
    visualType: 'contrast',
    highlight: { en: 'Human Accountability', de: 'Menschliche Verantwortung' },
  },
];
